name: PHP Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        phpVersion: ['8.1', '8.2', '8.3']

    steps:
    - name: Setup PHP with specific version of PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.phpVersion }}

    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v4
      env:
        XDEBUG_MODE: coverage
      with:
        configuration: phpunit.xml
        php_extensions: xdebug
        args: --coverage-clover ./coverage.xml

    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODE_COV_TOKEN }}
        files: ./coverage.xml
        verbose: true
